# Generated by Django 4.0 on 2021-12-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_reservations_number_of_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='reservations',
            old_name='Time',
            new_name='time',
        ),
    ]
