# Generated by Django 4.0 on 2021-12-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_date_reservations_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='title',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='user_id',
        ),
    ]
