# Generated by Django 4.0 on 2021-12-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rename_title_reservations_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='user',
            new_name='title',
        ),
    ]
