# Generated by Django 4.0 on 2021-12-13 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('restaurant', '0007_rename_user_reservations_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
